### ISSUE TITLE
win 11   faild to load driver

### ISSUE THREAD

**Issue by snltty** [ZeroMemoryEx/Blackout#5]
![QQ截图20240205141841](https://github.com/ZeroMemoryEx/Blackout/assets/10977033/7a469a5e-da9c-45fd-8e6e-76d3185f5956)

**Comment by ZeroMemoryEx** [comment]
Hello @snltty  sorry for late response  Microsoft has revoked the driver's certificate due to its increased use in malicious stuff thus making it unloadable, you might want to consider using [Terminator ](https://github.com/ZeroMemoryEx/Terminator) instead it has a valid certificate.

**Comment by sec13b** [comment]
avg delete instant
