### ISSUE TITLE
where is .sys driver source code?

### ISSUE THREAD

**Issue by jeycaschoe6** [ZeroMemoryEx/Blackout#8]
hi
how can i find source code of blackout.sys?
i need to bypass it

**Comment by ZeroMemoryEx** [comment]
Hello @jeycaschoe6 Blackout driver is not open-source and what do you mean by bypassing it?

**Comment by jeycaschoe6** [comment]
antiviruses get the .sys driver file
i want to use it

**Comment by ZeroMemoryEx** [comment]
@jeycaschoe6 Even if you have the source code, you can't load it due to driver signature enforcement. You need to sign it first.
